### ISSUE TITLE
Pokemanki: unable to open stats. page

### ISSUE THREAD

**Issue by dhanijon** [zjosua/Pokemanki#27] opened 2022-11-02 03:41 UTC
Hello, I've recently downloaded your updated pokemanki add-on, however whenever i click on the stats page I receive an error and am unable to use the add-on. I am on mac btw.

Here is the error message
-----------------------------------------
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-11-01 23:25:11
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/jondhani/Library/Application Support/Anki2/addons21/1041307953/main.py", line 151, in <lambda>
    statsDialog.form.web.loadFinished.connect(lambda _: _onStatsOpen(statsDialog))
  File "/Users/jondhani/Library/Application Support/Anki2/addons21/1041307953/main.py", line 145, in _onStatsOpen
    js = (addon_dir / "web.js").read_text()
  File "pathlib", line 1267, in read_text
  File "encodings.ascii", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)
```

**Comment by zjosua** [comment] 2022-11-02 06:06
Could you (or someone else who can reproduce the error) try if changing line 145 in main.py to `js = (addon_dir / "web.js").read_text(encoding="utf-8")` fixes the error?

According to the [pathlib docs](https://docs.python.org/3/library/functions.html#open), "the default encoding is platform dependent". I can't reproduce the error here on Debian GNU/Linux.

**Comment by zjosua** [comment] 2022-11-02 17:40
I just pushed the fix I mentioned above to another branch on commit https://github.com/zjosua/Pokemanki/commit/2a2634d4fd95b65733e49cd7037b5dbb48b479d9.
It would be nice if someone could test it on Mac before I merge it into the main branch.

**Comment by dhanijon** [comment] 2022-11-02 18:57
I modified line 145 with ur modification on the main.py file on my computer and now it works. Thanks!

**Closed as completed** 2022-11-03 16:47 UTC
