### ISSUE TITLE
No experience gained while doing cards

### ISSUE THREAD

**Issue by carlos1172** [zjosua/Pokemanki#3] opened 2022-10-02 00:46 UTC
#### Describe the bug
I'm getting no experience while doing cards. My Charmander which I found/caught at Level 9 with 9/20 experience stays at 9/20 experience even after doing a thousand cards.

#### To Reproduce
1. Have a deck of cards with tags
2. Select tags
3. Get a pokemon/egg
4. Stuck here

#### Expected behavior
Am I not supposed to gain experience while doing cards? What is the threshold? There are no settings to edit.

#### What I've tried
Disabling all other addons does nothing

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 12.5.1
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2022-10-02 05:59:47
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AJT Mortician ['1255924302', 2021-09-17T13:52, 'None', mod]
    AnKing Note Types Easy Customization ['952691989', 2022-09-06T01:23, 'None', mod]
    Anki Habitica for 21 ['1758045507', 2022-02-09T20:54, 'None', mod]
    Anki Simulator ['817108664', 2021-08-08T03:24, 'None', '']
    Anki-redesign ['308574457', 2022-08-23T02:25, 'None', mod]
    AnkiWebView Inspector ['31746032', 2022-04-09T03:44, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2021-08-12T00:57, 'None', '']
    Audiovisual Feedback ['231569866', 0, '0.8', mod]
    Batch Editing ['291119185', 2019-06-03T02:47, 'None', '']
    BetterSearch ['1052724801', 2022-01-26T06:25, 'None', '']
    Change Behaviour of Enter Return and Space When Answer Shown ['2018406030', 2021-05-19T00:47, 'None', mod]
    Correct Answers Graph ['993120073', 2022-03-15T04:52, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2022-07-28T21:54, 'None', mod]
    Delay siblings ['1369579727', 2022-06-04T07:05, 'None', mod]
    Find and Replace in Card templatesNotetypesHTML ['992153575', 2021-09-17T14:34, 'None', '']
    Full Screen Toggle ['1612375712', 2018-08-25T10:21, 'None', '']
    Hint Hotkeys ['1844908621', 2017-08-30T02:53, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2022-10-01T15:51, 'None', mod]
    Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T15:15, 'None', '']
    Large and Colorful Buttons ['1829090218', 2018-10-03T01:41, 'None', '']
    Learn now Button ['1021636467', 2021-10-16T02:21, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2022-08-29T04:21, 'None', '']
    Life Drain ['715575551', 2022-09-18T18:42, 'None', mod]
    Merge Notes ['1425504015', 2022-04-17T21:59, 'None', '']
    Open Add-on Folder Shortcut ['830940686', 2022-07-21T01:06, 'None', '']
    Postpone cards review ['1152543397', 2021-02-14T00:47, 'None', '']
    Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2022-08-05T19:01, 'None', mod]
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T14:26, 'None', '']
    Quick tagging 21 ['304770511', 2020-02-11T14:17, 'None', mod]
    Remove Duplicate Cards ['95590040', 2021-05-06T02:12, 'None', '']
    Remove card history ['2089200096', 2018-04-23T14:50, 'None', '']
    Reset Ease ['947935257', 2020-12-27T22:59, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']
    Search and Replace Tags ['138501288', 2017-08-30T02:58, 'None', '']
    Speed Focus Mode ['speed_focus_mode', 2021-10-01T00:12, 'None', mod]
    Straight Reward ['957961234', 2022-04-01T03:37, 'None', '']
    True Retention ['613684242', 2017-11-20T04:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1021636467 1052724801 1097423555 111623432 1152543397 1210908941 1255924302 1369579727 1374772155 138501288 1425504015 149004221 1612375712 1758045507 1771074083 1829090218 1844908621 1949865265 2018406030 2089200096 231569866 266436365 291119185 304770511 308574457 31746032 613684242 715575551 817108664 830940686 947935257 952691989 95590040 957961234 992153575 993120073
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

What operating system are you using?
- OS: MacOS Monterey
- version: 12.5.1

**Comment by zjosua** [comment] 2022-10-04 18:24
Please excuese the rather basic question, but did you study cards that are tagged with the tag you got the Pokémon for?

**Comment by carlos1172** [comment] 2022-10-04 20:57
Yes

Regards,
Carlos Resurreccion

**Comment by zjosua** [comment] 2022-10-08 11:48
I can't reproduce the problem; my tagmon level just fine.
Could you run `pp(mw.col.get_config("pokemanki"))` in Anki's debug console and paste the output here?

**Comment by carlos1172** [comment] 2022-10-09 18:59
>>> pp(mw.col.get_config("pokemanki"))
{'alolanlist': [],
 'decks_or_tags': 'tags',
 'everstonelist': [],
 'everstonepokemonlist': [],
 'evolution_thresholds': {'decks': [100, 250, 500, 750, 1000],
                          'tags': [50, 125, 250, 375, 500]},
 'megastonelist': [],
 'pokemon_list': [],
 'prestigelist': [],
 'tagmon_list': [['Charmander', 'YL6', 9.33], ['Charmander', 'YL6', 9.33]],
 'tags': ['YL6'],
 'trades': []}

**Comment by carlos1172** [comment] 2022-10-09 19:12
When trying to edit nicknames:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.5
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-10 03:11:23
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/carlos/Library/Application Support/Anki2/addons21/1041307953/pokemon.py", line 22, in Nickname
    deckname = mw.col.decks.name(item[1])
  File "anki.decks", line 376, in name
  File "anki.decks", line 237, in get
ValueError: invalid literal for int() with base 10: 'YL6'

**Comment by carlos1172** [comment] 2022-10-09 19:37
Everytime I open the stats screen, Charmander Level 9 9.33 gets duplicated.


>>> pp(mw.col.get_config("pokemanki"))
{'alolanlist': [],
 'decks_or_tags': 'tags',
 'everstonelist': [],
 'everstonepokemonlist': [],
 'evolution_thresholds': {'decks': [100, 250, 500, 750, 1000],
                          'tags': [50, 125, 250, 375, 500]},
 'megastonelist': [],
 'pokemon_list': [],
 'prestigelist': [],
 'tagmon_list': [['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33],
                 ['Charmander', 'YL6', 9.33]],
 'tags': ['YL6'],
 'trades': []}

**Comment by zjosua** [comment] 2022-10-09 20:13
> Everytime I open the stats screen, Charmander Level 9 9.33 gets duplicated.

Yes we know about that. See #4.
Please stop spamming this thread with unrelated issues and in general check whether your issue has been reported before.

**Comment by carlos1172** [comment] 2022-10-09 20:14
> 

Got it, sorry. Will be on standby should you require any more information.

**Comment by carlos1172** [comment] 2022-10-10 02:17
Excuse my ignorance, but how should tagmon level up? By doing cards with the specified tag, or by adding tagging more cards with that tag?

I just did some more tagging right now while organizing my deck, and my tagmon charmander went from 30% to 95% exp.

**Comment by zjosua** [comment] 2022-10-10 19:19
The Tagmon gain XP for reviews of cards with the respective tag.
Past reviews of the newly tagged cards also give XP.

**Comment by zjosua** [comment] 2022-11-17 20:17
Hi @carlos1172 
Is this still an issue?

**Comment by carlos1172** [comment] 2022-11-17 23:14
> Hi @carlos1172 
> 
> Is this still an issue?

Sorry. I quit med school so I don't know.

**Comment by zjosua** [comment] 2022-11-18 03:54
Ok. Thanks for the swift reply.
Closing this for now. If anyone has the same issue, feel free to reopen.

**Closed as completed by zjosua** 2022-11-18 03:54 UTC
Labels: bug
